version: 2.1
executors:
  node14:
    docker:
    - image: circleci/node:14
    environment:
      NPM_CONFIG_PREFIX: ~/.npm-global
  ubuntu16:
    docker:
    - image: ubuntu:16.04
    environment:
    - GOOGLE_APP_ID: ccfggkjabjahcjoljmgmklhpaccedipo

orbs:
  puppeteer: threetreeslight/puppeteer@0.1.2

commands:
  setup:
    steps:
    - checkout
    # - restore_cache:
    #     keys:
    #     - v1-dependencies-{{ arch }}-{{ checksum "package-lock.json" }}
    - run:
        name: install latest npm
        command: sudo npm -g install npm
    - run:
        name: Installing Dependencies
        command: npm ci
    # - save_cache:
    #     paths:
    #     - node_modules
    #     key: v1-dependencies-{{ arch }}-{{ checksum "package-lock.json" }}
    - run:
        name: prepare test git user
        command: git config --global user.email "circleci@example.com" && git config --global user.name "CircleCi Build"

jobs:
  build:
    executor: node14
    steps:
    - setup
    - run: mkdir junit
    - run:
        name: Lint
        command: npm run lint
    - puppeteer/install
    - run:
        name: Test
        command: npm run test
    - store_test_results:
        path: junit
    - store_artifacts:
        path: junit
  semantic-release:
    executor: node14
    steps:
      - setup
      - run:
          name: revert changes to package-lock.json
          command: git checkout -- package-lock.json
      - run:
          name: Semantic Release
          command: npm run semantic-release
  deploy-extension:
    executor: ubuntu16
    steps:
      - run:
          name: "Install Dependencies for Chrome Web Store Deployment"
          command: |
            apt-get update
            apt-get -y install curl jq
      - run:
          name: Build Chrome Extension
          command: npm run build:chrome
      - run:
          name: "Upload & Publish Extension to Chrome Web Store"
          command: |
            ACCESS_TOKEN=$(curl "https://accounts.google.com/o/oauth2/token" -d "client_id=${GOOGLE_CLIENT_ID}&client_secret=${GOOGLE_CLIENT_SECRET}&refresh_token=${GOOGLE_REFRESH_TOKEN}&grant_type=refresh_token&redirect_uri=urn:ietf:wg:oauth:2.0:oob" | jq -r .access_token)
            curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -X PUT -T ./dist/chrome.zip -v "https://www.googleapis.com/upload/chromewebstore/v1.1/items/${GOOGLE_APP_ID}"
            curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -H "Content-Length: 0" -X POST -v "https://www.googleapis.com/chromewebstore/v1.1/items/${GOOGLE_APP_ID}/publish"

workflows:
  version: 2
  build:
    jobs:
    - build
    - semantic-release:
        context: Project Helix
        requires:
          - build
        filters:
          branches:
            only: main
    - deploy-extension:
        context: Project Helix
        filters:
          branches:
            only: main
          tags:
            only: /v[\d|\.]*/
