name: Branch Release
on: push

jobs:
  branch-release:
    runs-on: ubuntu-latest
    if: "${{ !endsWith(github.ref, '/main') && !contains(github.event.head_commit.message, '[skip ci]') }}"
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.SSH-KEY }}
      - name: Pack chrome extension
        run: |
          if [ "`git status -s src/extension`" != "" ]; then
            echo "Packing chrome extension"
            # write private key file
            echo "{{ secrets.CHROME_EXT_PEM }}" > .extension.pem
            chmod 600 .extension.pem
            # pack crx file
            npm install --no-save crx3
            ./node_modules/.bin/crx3 ./src/extension \
              -p ./.extension.pem \
              -o ./src/sidekick/extension.crx \
              -x ./src/sidekick/extension.xml \
              --crxURL https://www.hlx.live/tools/sidekick/extension.crx
          else
            echo "No changes in extension detected"
          fi
      - name: Checkout target repo
        uses: actions/checkout@v2
        with:
          repository: adobe/helix-pages
          token: ${{ secrets.PAT }}
          fetch-depth: 0
          clean: true
          path: _target
      - name: Copy changes from source to target repo and create branch commit
        run: |
          cd _target
          # generate target branch name
          IFS='/' read -ra temp <<< "${{ github.ref }}"
          targetbranch=sidekick-${temp[2]}
          # create and/or switch to target branch and apply changes
          git switch ${targetbranch} || git checkout -b ${targetbranch}
          cp ../src/sidekick/* tools/sidekick/
          cp ../docs/API.md tools/sidekick/
          git add tools/sidekick/*
          if [ "`git status -s`" != "" ]; then
            echo Changes: `git status -s`
            # push changes to target branch
            git config user.name ${{ github.actor }}
            git config user.email ${{ github.actor }}@users.noreply.github.com
            git config user.password ${{ secrets.PAT }}
            git commit -m"chore(sidekick): branch release [skip ci]"
            git push origin ${targetbranch}
          else
            echo No changes to commit
          fi
